-- SRM attendance — unified PostgreSQL schema
-- identity  = Phase 1 (capture, embeddings, identification events)
-- attendance = Phase 2 (timetable, marks, users, dashboard)
--
-- Apply after creating the database:
--   psql -U postgres -d srm_attendance -f DB/init_postgresql.sql
--
-- Changes vs the MariaDB dump (srmvec_ai_attendance.sql):
--   * One engine (Postgres + pgvector), two schemas — not MySQL + Postgres
--   * Embeddings only in identity.face_embeddings as VECTOR(512)
--   * No camera passwords / RTSP credentials
--   * university_id is the join key to the identification pipeline
--   * identification event_id is the ingest idempotency key
--   * Present/Late/Absent is not auto-forced by a duration trigger
--   * Summary functions use NULLIF to avoid divide-by-zero
--   * Defaulter generation upserts; it does not wipe history
--   * Consent / opted_out live on identity.students
--   * Unknown-face review does not store images by default

\set ON_ERROR_STOP on

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS attendance;

COMMENT ON SCHEMA identity IS 'Phase 1: cameras, students, embeddings, identification events';
COMMENT ON SCHEMA attendance IS 'Phase 2: academic structure, attendance marks, dashboard users';

-- ---------------------------------------------------------------------------
-- Academic structure (attendance)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.departments (
    department_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code TEXT NOT NULL UNIQUE,
    department_name TEXT NOT NULL,
    hod_staff_id    BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.programs (
    program_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_code    TEXT NOT NULL UNIQUE,
    program_name    TEXT NOT NULL,
    duration_years  INTEGER NOT NULL CHECK (duration_years > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.academic_years (
    academic_year_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            TEXT NOT NULL UNIQUE,
    start_date       DATE NOT NULL,
    end_date         DATE NOT NULL,
    is_active        BOOLEAN NOT NULL DEFAULT false,
    CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS attendance.semesters (
    semester_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    semester_no       INTEGER NOT NULL CHECK (semester_no BETWEEN 1 AND 10),
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    UNIQUE (academic_year_id, semester_no),
    CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS attendance.subject_categories (
    category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS attendance.subjects (
    subject_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code    TEXT NOT NULL UNIQUE,
    subject_name    TEXT NOT NULL,
    category_id     INTEGER REFERENCES attendance.subject_categories (category_id),
    department_id   INTEGER NOT NULL REFERENCES attendance.departments (department_id),
    semester_no     INTEGER,
    credits         NUMERIC(3, 1),
    total_hours     INTEGER,
    is_lab          BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS attendance.classrooms (
    classroom_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number  TEXT NOT NULL,
    block_name   TEXT,
    floor_no     INTEGER,
    capacity     INTEGER,
    has_cctv     BOOLEAN NOT NULL DEFAULT true,
    remarks      TEXT,
    UNIQUE (block_name, room_number)
);

CREATE TABLE IF NOT EXISTS attendance.periods (
    period_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_no         INTEGER NOT NULL UNIQUE,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL,
    duration_minutes  INTEGER NOT NULL CHECK (duration_minutes > 0),
    CHECK (end_time > start_time)
);

CREATE TABLE IF NOT EXISTS attendance.sections (
    section_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id     INTEGER NOT NULL REFERENCES attendance.departments (department_id),
    program_id        INTEGER NOT NULL REFERENCES attendance.programs (program_id),
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    semester_id       INTEGER NOT NULL REFERENCES attendance.semesters (semester_id),
    section_name      TEXT NOT NULL,
    strength          INTEGER NOT NULL DEFAULT 0 CHECK (strength >= 0),
    UNIQUE (department_id, program_id, academic_year_id, semester_id, section_name)
);

CREATE TABLE IF NOT EXISTS attendance.users (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    role_id         INTEGER NOT NULL REFERENCES attendance.roles (role_id),
    department_id   INTEGER REFERENCES attendance.departments (department_id),
    first_name      TEXT NOT NULL,
    last_name       TEXT,
    email           TEXT UNIQUE,
    mobile          TEXT,
    status          TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.user_sessions (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES attendance.users (user_id) ON DELETE CASCADE,
    session_token TEXT NOT NULL UNIQUE,
    login_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    logout_at     TIMESTAMPTZ,
    ip_address    INET,
    device        TEXT
);

-- ---------------------------------------------------------------------------
-- Identity (Phase 1)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS identity.cameras (
    camera_id       TEXT PRIMARY KEY,
    location_label  TEXT NOT NULL,
    source_ref      TEXT NOT NULL,
    classroom_id    INTEGER REFERENCES attendance.classrooms (classroom_id),
    roi             REAL[4],
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN identity.cameras.source_ref IS
    'Lookup key for the secret store. Never store RTSP passwords in this table.';

CREATE TABLE IF NOT EXISTS identity.students (
    student_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    university_id      TEXT UNIQUE NOT NULL,
    full_name          TEXT NOT NULL,
    user_id            BIGINT UNIQUE REFERENCES attendance.users (user_id),
    section_id         INTEGER REFERENCES attendance.sections (section_id),
    register_no        TEXT UNIQUE,
    admission_no       TEXT,
    roll_no            TEXT,
    batch_year         INTEGER,
    gender             TEXT CHECK (gender IN ('male', 'female', 'other')),
    dob                DATE,
    enrollment_status  TEXT NOT NULL DEFAULT 'active'
        CHECK (enrollment_status IN ('active', 'withdrawn', 'graduated', 'opted_out')),
    consent_granted_at TIMESTAMPTZ,
    face_registered    BOOLEAN NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN identity.students.university_id IS
    'SIS identifier. This is the join key carried on identification events.';

CREATE TABLE IF NOT EXISTS identity.face_embeddings (
    embedding_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id    UUID NOT NULL REFERENCES identity.students (student_id) ON DELETE CASCADE,
    embedding     VECTOR(512) NOT NULL,
    model_version TEXT NOT NULL,
    source        TEXT NOT NULL CHECK (source IN ('enrollment', 're-enrollment')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS face_embeddings_model_version_idx
    ON identity.face_embeddings (model_version);
CREATE INDEX IF NOT EXISTS face_embeddings_student_idx
    ON identity.face_embeddings (student_id);

CREATE TABLE IF NOT EXISTS identity.identification_events (
    event_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id        UUID NOT NULL REFERENCES identity.students (student_id),
    camera_id         TEXT NOT NULL REFERENCES identity.cameras (camera_id),
    confidence        REAL NOT NULL,
    frame_captured_at TIMESTAMPTZ NOT NULL,
    matched_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    model_version     TEXT NOT NULL,
    track_id          INTEGER,
    consumed          BOOLEAN NOT NULL DEFAULT false,
    consumed_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS identification_events_unconsumed_idx
    ON identity.identification_events (matched_at)
    WHERE NOT consumed;

CREATE INDEX IF NOT EXISTS identification_events_student_time_idx
    ON identity.identification_events (student_id, frame_captured_at DESC);

CREATE TABLE IF NOT EXISTS identity.unresolved_detections (
    detection_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    camera_id         TEXT NOT NULL REFERENCES identity.cameras (camera_id),
    frame_captured_at TIMESTAMPTZ NOT NULL,
    logged_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    track_id          INTEGER,
    stage             TEXT NOT NULL CHECK (stage IN ('quality', 'match')),
    reason            TEXT NOT NULL,
    detector_score    REAL NOT NULL,
    box               REAL[4] NOT NULL,
    best_similarity   REAL,
    margin            REAL,
    quality_metrics   JSONB NOT NULL DEFAULT '{}'::jsonb,
    model_version     TEXT NOT NULL,
    embedding         VECTOR(512)
);

CREATE INDEX IF NOT EXISTS unresolved_detections_time_idx
    ON identity.unresolved_detections (frame_captured_at DESC);
CREATE INDEX IF NOT EXISTS unresolved_detections_stage_idx
    ON identity.unresolved_detections (stage);

CREATE OR REPLACE FUNCTION identity.mark_face_registered()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE identity.students
    SET face_registered = true
    WHERE student_id = NEW.student_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_face_registered ON identity.face_embeddings;
CREATE TRIGGER trg_face_registered
    AFTER INSERT ON identity.face_embeddings
    FOR EACH ROW
    EXECUTE FUNCTION identity.mark_face_registered();

-- ---------------------------------------------------------------------------
-- Staff and timetable
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.staff (
    staff_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES attendance.users (user_id) ON DELETE CASCADE,
    staff_code       TEXT NOT NULL UNIQUE,
    designation      TEXT,
    department_id    INTEGER NOT NULL REFERENCES attendance.departments (department_id),
    employee_type    TEXT NOT NULL DEFAULT 'regular'
        CHECK (employee_type IN ('regular', 'contract', 'visiting')),
    status           TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'medical_leave', 'relieved')),
    joining_date     DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE attendance.departments
    DROP CONSTRAINT IF EXISTS departments_hod_staff_id_fkey;
ALTER TABLE attendance.departments
    ADD CONSTRAINT departments_hod_staff_id_fkey
    FOREIGN KEY (hod_staff_id) REFERENCES attendance.staff (staff_id);

CREATE TABLE IF NOT EXISTS attendance.staff_sections (
    staff_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id         BIGINT NOT NULL REFERENCES attendance.staff (staff_id) ON DELETE CASCADE,
    section_id       INTEGER NOT NULL REFERENCES attendance.sections (section_id) ON DELETE CASCADE,
    role             TEXT NOT NULL CHECK (role IN ('subject_staff', 'class_advisor', 'mentor')),
    UNIQUE (staff_id, section_id, role)
);

CREATE TABLE IF NOT EXISTS attendance.staff_subjects (
    staff_subject_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id          BIGINT NOT NULL REFERENCES attendance.staff (staff_id) ON DELETE CASCADE,
    subject_id        BIGINT NOT NULL REFERENCES attendance.subjects (subject_id),
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    semester_id       INTEGER NOT NULL REFERENCES attendance.semesters (semester_id),
    UNIQUE (staff_id, subject_id, academic_year_id, semester_id)
);

CREATE TABLE IF NOT EXISTS attendance.timetable (
    timetable_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    semester_id       INTEGER NOT NULL REFERENCES attendance.semesters (semester_id),
    section_id        INTEGER NOT NULL REFERENCES attendance.sections (section_id),
    subject_id        BIGINT NOT NULL REFERENCES attendance.subjects (subject_id),
    staff_id          BIGINT NOT NULL REFERENCES attendance.staff (staff_id),
    classroom_id      INTEGER NOT NULL REFERENCES attendance.classrooms (classroom_id),
    day_of_week       INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    period_id         INTEGER NOT NULL REFERENCES attendance.periods (period_id),
    is_active         BOOLEAN NOT NULL DEFAULT true,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS timetable_active_slot_idx
    ON attendance.timetable (section_id, day_of_week, period_id)
    WHERE is_active;

CREATE TABLE IF NOT EXISTS attendance.timetable_history (
    history_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id  BIGINT NOT NULL REFERENCES attendance.timetable (timetable_id),
    modified_by   BIGINT REFERENCES attendance.users (user_id),
    old_staff_id  BIGINT REFERENCES attendance.staff (staff_id),
    new_staff_id  BIGINT REFERENCES attendance.staff (staff_id),
    modified_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.class_swaps (
    swap_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_staff_id   BIGINT NOT NULL REFERENCES attendance.staff (staff_id),
    replacement_staff_id BIGINT NOT NULL REFERENCES attendance.staff (staff_id),
    timetable_id        BIGINT NOT NULL REFERENCES attendance.timetable (timetable_id),
    swap_date           DATE NOT NULL,
    approved_by         BIGINT REFERENCES attendance.users (user_id),
    status              TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected')),
    UNIQUE (timetable_id, swap_date)
);

CREATE TABLE IF NOT EXISTS attendance.holidays (
    holiday_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    holiday_name      TEXT NOT NULL,
    holiday_date      DATE NOT NULL,
    holiday_type      TEXT CHECK (holiday_type IN ('government', 'college', 'exam', 'festival')),
    UNIQUE (academic_year_id, holiday_date)
);

CREATE TABLE IF NOT EXISTS attendance.working_days (
    working_day_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id  INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    work_date         DATE NOT NULL,
    is_working        BOOLEAN NOT NULL DEFAULT true,
    UNIQUE (academic_year_id, work_date)
);

-- ---------------------------------------------------------------------------
-- Attendance marks (Phase 2 consumes identification events into these tables)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.records (
    attendance_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         UUID NOT NULL REFERENCES identity.students (student_id),
    timetable_id       BIGINT NOT NULL REFERENCES attendance.timetable (timetable_id),
    attendance_date    DATE NOT NULL,
    entry_time         TIMESTAMPTZ,
    exit_time          TIMESTAMPTZ,
    duration_minutes   INTEGER,
    attendance_source  TEXT NOT NULL DEFAULT 'ai'
        CHECK (attendance_source IN ('ai', 'manual', 'imported')),
    confidence         REAL,
    status             TEXT NOT NULL
        CHECK (status IN ('present', 'absent', 'late', 'excused')),
    marked_by          BIGINT REFERENCES attendance.users (user_id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, timetable_id, attendance_date)
);

CREATE INDEX IF NOT EXISTS records_student_idx ON attendance.records (student_id);
CREATE INDEX IF NOT EXISTS records_date_idx ON attendance.records (attendance_date);

CREATE TABLE IF NOT EXISTS attendance.ingested_events (
    ingest_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id               UUID NOT NULL UNIQUE
        REFERENCES identity.identification_events (event_id),
    attendance_id          BIGINT REFERENCES attendance.records (attendance_id),
    ignored_reason         TEXT,
    ingested_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE attendance.ingested_events IS
    'Idempotency for Phase 2: each identification event is applied at most once.';

CREATE TABLE IF NOT EXISTS attendance.corrections (
    correction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id   BIGINT NOT NULL REFERENCES attendance.records (attendance_id),
    old_status      TEXT NOT NULL,
    new_status      TEXT NOT NULL,
    reason          TEXT NOT NULL,
    corrected_by    BIGINT NOT NULL REFERENCES attendance.users (user_id),
    corrected_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.status_history (
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      UUID NOT NULL REFERENCES identity.students (student_id),
    attendance_date DATE NOT NULL,
    timetable_id    BIGINT NOT NULL REFERENCES attendance.timetable (timetable_id),
    previous_status TEXT,
    new_status      TEXT NOT NULL,
    modified_by     BIGINT REFERENCES attendance.users (user_id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION attendance.log_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO attendance.status_history (
            student_id, attendance_date, timetable_id,
            previous_status, new_status, modified_by
        ) VALUES (
            NEW.student_id, NEW.attendance_date, NEW.timetable_id,
            OLD.status, NEW.status, NEW.marked_by
        );
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_attendance_status_history ON attendance.records;
CREATE TRIGGER trg_attendance_status_history
    AFTER UPDATE ON attendance.records
    FOR EACH ROW
    EXECUTE FUNCTION attendance.log_status_change();

CREATE TABLE IF NOT EXISTS attendance.subject_summary (
    summary_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         UUID NOT NULL REFERENCES identity.students (student_id),
    subject_id         BIGINT NOT NULL REFERENCES attendance.subjects (subject_id),
    academic_year_id   INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    semester_id        INTEGER NOT NULL REFERENCES attendance.semesters (semester_id),
    total_classes      INTEGER NOT NULL DEFAULT 0,
    attended_classes   INTEGER NOT NULL DEFAULT 0,
    absent_classes     INTEGER NOT NULL DEFAULT 0,
    late_classes       INTEGER NOT NULL DEFAULT 0,
    percentage         NUMERIC(5, 2),
    last_updated       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, subject_id, semester_id)
);

CREATE TABLE IF NOT EXISTS attendance.daily_summary (
    summary_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_date         DATE NOT NULL,
    department_id           INTEGER NOT NULL REFERENCES attendance.departments (department_id),
    section_id              INTEGER NOT NULL REFERENCES attendance.sections (section_id),
    total_students          INTEGER NOT NULL DEFAULT 0,
    present_count           INTEGER NOT NULL DEFAULT 0,
    absent_count            INTEGER NOT NULL DEFAULT 0,
    late_count              INTEGER NOT NULL DEFAULT 0,
    attendance_percentage   NUMERIC(5, 2),
    UNIQUE (attendance_date, section_id)
);

CREATE TABLE IF NOT EXISTS attendance.monthly_summary (
    summary_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id        INTEGER NOT NULL REFERENCES attendance.academic_years (academic_year_id),
    month_no                INTEGER NOT NULL CHECK (month_no BETWEEN 1 AND 12),
    department_id           INTEGER NOT NULL REFERENCES attendance.departments (department_id),
    section_id              INTEGER NOT NULL REFERENCES attendance.sections (section_id),
    total_classes           INTEGER,
    total_present           INTEGER,
    total_absent            INTEGER,
    attendance_percentage   NUMERIC(5, 2),
    UNIQUE (academic_year_id, month_no, section_id)
);

CREATE TABLE IF NOT EXISTS attendance.alerts (
    alert_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   UUID NOT NULL REFERENCES identity.students (student_id),
    subject_id   BIGINT NOT NULL REFERENCES attendance.subjects (subject_id),
    semester_id  INTEGER NOT NULL REFERENCES attendance.semesters (semester_id),
    percentage   NUMERIC(5, 2) NOT NULL,
    alert_type   TEXT NOT NULL CHECK (alert_type IN ('below75', 'below60', 'critical')),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, subject_id, semester_id)
);

-- ---------------------------------------------------------------------------
-- Enrollment workflow (dashboard). Embeddings still live only in identity.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.registration_sessions (
    session_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     UUID NOT NULL REFERENCES identity.students (student_id) ON DELETE CASCADE,
    registered_by  BIGINT REFERENCES attendance.users (user_id),
    registered_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.registration_images (
    image_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES attendance.registration_sessions (session_id) ON DELETE CASCADE,
    student_id   UUID NOT NULL REFERENCES identity.students (student_id) ON DELETE CASCADE,
    pose         TEXT CHECK (pose IN ('front', 'left', 'right')),
    storage_ref  TEXT NOT NULL,
    quality_ok   BOOLEAN NOT NULL DEFAULT false,
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN attendance.registration_images.storage_ref IS
    'Object-store key, not a vector. Identity service reads this to embed.';

CREATE TABLE IF NOT EXISTS attendance.unknown_reviews (
    review_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detection_id  UUID NOT NULL UNIQUE
        REFERENCES identity.unresolved_detections (detection_id),
    reviewed      BOOLEAN NOT NULL DEFAULT false,
    reviewed_by   BIGINT REFERENCES attendance.users (user_id),
    remarks       TEXT,
    reviewed_at   TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS attendance.camera_health_logs (
    log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id        TEXT NOT NULL REFERENCES identity.cameras (camera_id) ON DELETE CASCADE,
    status           TEXT NOT NULL CHECK (status IN ('online', 'offline')),
    network_latency_ms INTEGER,
    recorded_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.student_parents (
    parent_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      UUID NOT NULL REFERENCES identity.students (student_id) ON DELETE CASCADE,
    father_name     TEXT,
    mother_name     TEXT,
    guardian_name   TEXT,
    father_mobile   TEXT,
    mother_mobile   TEXT,
    guardian_mobile TEXT,
    email           TEXT
);

CREATE TABLE IF NOT EXISTS attendance.notifications (
    notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES attendance.users (user_id) ON DELETE CASCADE,
    title             TEXT NOT NULL,
    message           TEXT NOT NULL,
    notification_type TEXT NOT NULL
        CHECK (notification_type IN ('attendance', 'leave', 'announcement', 'system')),
    is_read           BOOLEAN NOT NULL DEFAULT false,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.email_queue (
    email_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  UUID REFERENCES identity.students (student_id),
    email       TEXT NOT NULL,
    subject     TEXT NOT NULL,
    message     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'failed')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS attendance.audit_logs (
    audit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES attendance.users (user_id),
    action      TEXT NOT NULL,
    table_name  TEXT,
    record_id   TEXT,
    action_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip_address  INET
);

CREATE TABLE IF NOT EXISTS attendance.report_exports (
    export_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exported_by  BIGINT NOT NULL REFERENCES attendance.users (user_id),
    report_name  TEXT NOT NULL,
    report_type  TEXT NOT NULL CHECK (report_type IN ('excel', 'pdf')),
    file_path    TEXT,
    exported_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance.system_settings (
    setting_key   TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    description   TEXT
);

-- ---------------------------------------------------------------------------
-- Summary functions (safe arithmetic, no full-table alert wipes)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION attendance.refresh_subject_summary()
RETURNS void
LANGUAGE sql
AS $$
    INSERT INTO attendance.subject_summary (
        student_id, subject_id, academic_year_id, semester_id,
        total_classes, attended_classes, absent_classes, late_classes, percentage, last_updated
    )
    SELECT
        r.student_id,
        t.subject_id,
        t.academic_year_id,
        t.semester_id,
        COUNT(*)::INTEGER,
        COUNT(*) FILTER (WHERE r.status IN ('present', 'late'))::INTEGER,
        COUNT(*) FILTER (WHERE r.status = 'absent')::INTEGER,
        COUNT(*) FILTER (WHERE r.status = 'late')::INTEGER,
        ROUND(
            100.0 * COUNT(*) FILTER (WHERE r.status IN ('present', 'late'))
            / NULLIF(COUNT(*), 0),
            2
        ),
        now()
    FROM attendance.records r
    JOIN attendance.timetable t ON t.timetable_id = r.timetable_id
    GROUP BY r.student_id, t.subject_id, t.academic_year_id, t.semester_id
    ON CONFLICT (student_id, subject_id, semester_id) DO UPDATE
    SET total_classes    = EXCLUDED.total_classes,
        attended_classes = EXCLUDED.attended_classes,
        absent_classes   = EXCLUDED.absent_classes,
        late_classes     = EXCLUDED.late_classes,
        percentage       = EXCLUDED.percentage,
        last_updated     = now();
$$;

CREATE OR REPLACE FUNCTION attendance.refresh_daily_summary(p_date DATE)
RETURNS void
LANGUAGE sql
AS $$
    INSERT INTO attendance.daily_summary (
        attendance_date, department_id, section_id,
        total_students, present_count, absent_count, late_count, attendance_percentage
    )
    SELECT
        p_date,
        sec.department_id,
        sec.section_id,
        COUNT(DISTINCT s.student_id)::INTEGER,
        COUNT(r.attendance_id) FILTER (WHERE r.status IN ('present', 'late'))::INTEGER,
        COUNT(r.attendance_id) FILTER (WHERE r.status = 'absent')::INTEGER,
        COUNT(r.attendance_id) FILTER (WHERE r.status = 'late')::INTEGER,
        ROUND(
            100.0 * COUNT(r.attendance_id) FILTER (WHERE r.status IN ('present', 'late'))
            / NULLIF(COUNT(r.attendance_id), 0),
            2
        )
    FROM attendance.sections sec
    JOIN identity.students s ON s.section_id = sec.section_id
        AND s.enrollment_status = 'active'
    LEFT JOIN attendance.records r
        ON r.student_id = s.student_id
       AND r.attendance_date = p_date
    GROUP BY sec.department_id, sec.section_id
    ON CONFLICT (attendance_date, section_id) DO UPDATE
    SET total_students          = EXCLUDED.total_students,
        present_count           = EXCLUDED.present_count,
        absent_count            = EXCLUDED.absent_count,
        late_count              = EXCLUDED.late_count,
        attendance_percentage   = EXCLUDED.attendance_percentage;
$$;

CREATE OR REPLACE FUNCTION attendance.refresh_defaulter_alerts()
RETURNS void
LANGUAGE sql
AS $$
    INSERT INTO attendance.alerts (student_id, subject_id, semester_id, percentage, alert_type)
    SELECT
        student_id,
        subject_id,
        semester_id,
        percentage,
        CASE
            WHEN percentage < 50 THEN 'critical'
            WHEN percentage < 60 THEN 'below60'
            ELSE 'below75'
        END
    FROM attendance.subject_summary
    WHERE percentage < 75
    ON CONFLICT (student_id, subject_id, semester_id) DO UPDATE
    SET percentage   = EXCLUDED.percentage,
        alert_type   = EXCLUDED.alert_type,
        generated_at = now();
$$;

-- ---------------------------------------------------------------------------
-- Dashboard views
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW attendance.vw_student_attendance AS
SELECT
    s.student_id,
    s.university_id,
    s.full_name,
    sub.subject_name,
    COUNT(r.attendance_id) AS total,
    COUNT(r.attendance_id) FILTER (WHERE r.status IN ('present', 'late')) AS attended,
    ROUND(
        100.0 * COUNT(r.attendance_id) FILTER (WHERE r.status IN ('present', 'late'))
        / NULLIF(COUNT(r.attendance_id), 0),
        2
    ) AS percentage
FROM identity.students s
LEFT JOIN attendance.records r ON r.student_id = s.student_id
LEFT JOIN attendance.timetable t ON t.timetable_id = r.timetable_id
LEFT JOIN attendance.subjects sub ON sub.subject_id = t.subject_id
GROUP BY s.student_id, s.university_id, s.full_name, sub.subject_id, sub.subject_name;

CREATE OR REPLACE VIEW attendance.vw_defaulters AS
SELECT *
FROM attendance.vw_student_attendance
WHERE percentage < 75;

CREATE OR REPLACE VIEW attendance.vw_daily_report AS
SELECT
    r.attendance_date,
    sub.subject_name,
    sec.section_name,
    COUNT(*) FILTER (WHERE r.status IN ('present', 'late')) AS present,
    COUNT(*) FILTER (WHERE r.status = 'late') AS late,
    COUNT(*) FILTER (WHERE r.status = 'absent') AS absent
FROM attendance.records r
JOIN attendance.timetable t ON t.timetable_id = r.timetable_id
JOIN attendance.subjects sub ON sub.subject_id = t.subject_id
JOIN attendance.sections sec ON sec.section_id = t.section_id
GROUP BY r.attendance_date, sub.subject_id, sub.subject_name, sec.section_id, sec.section_name;

CREATE OR REPLACE VIEW attendance.vw_camera_dashboard AS
SELECT
    c.camera_id,
    c.location_label,
    c.enabled,
    cl.room_number,
    cl.block_name
FROM identity.cameras c
LEFT JOIN attendance.classrooms cl ON cl.classroom_id = c.classroom_id;

CREATE OR REPLACE VIEW attendance.vw_unknown_reviews AS
SELECT
    u.detection_id,
    u.camera_id,
    u.frame_captured_at,
    u.stage,
    u.reason,
    u.best_similarity,
    COALESCE(r.reviewed, false) AS reviewed,
    r.remarks
FROM identity.unresolved_detections u
LEFT JOIN attendance.unknown_reviews r ON r.detection_id = u.detection_id;

-- ---------------------------------------------------------------------------
-- Seed (no secrets, no working passwords)
-- ---------------------------------------------------------------------------

INSERT INTO attendance.roles (role_id, role_name, description) OVERRIDING SYSTEM VALUE VALUES
    (1, 'super_admin', 'Complete system control'),
    (2, 'admin', 'Department administration'),
    (3, 'hod', 'Department monitoring'),
    (4, 'class_advisor', 'Class management'),
    (5, 'staff', 'Faculty access'),
    (6, 'student', 'Student portal')
ON CONFLICT (role_id) DO NOTHING;

INSERT INTO attendance.departments (department_id, department_code, department_name) OVERRIDING SYSTEM VALUE VALUES
    (1, 'CSE', 'Computer Science and Engineering'),
    (2, 'MCA', 'Master of Computer Applications'),
    (3, 'IT', 'Information Technology'),
    (4, 'ECE', 'Electronics and Communication Engineering'),
    (5, 'EEE', 'Electrical and Electronics Engineering'),
    (6, 'MECH', 'Mechanical Engineering')
ON CONFLICT (department_id) DO NOTHING;

INSERT INTO attendance.programs (program_id, program_code, program_name, duration_years) OVERRIDING SYSTEM VALUE VALUES
    (1, 'BE-CSE', 'B.E Computer Science and Engineering', 4),
    (2, 'MCA', 'Master of Computer Applications', 2)
ON CONFLICT (program_id) DO NOTHING;

INSERT INTO attendance.academic_years (academic_year_id, label, start_date, end_date, is_active) OVERRIDING SYSTEM VALUE VALUES
    (1, '2026-2027', '2026-07-01', '2027-06-30', true)
ON CONFLICT (academic_year_id) DO NOTHING;

INSERT INTO attendance.semesters (semester_id, academic_year_id, semester_no, start_date, end_date) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 1, '2026-07-01', '2026-12-15'),
    (3, 1, 3, '2026-07-01', '2026-12-15')
ON CONFLICT (semester_id) DO NOTHING;

INSERT INTO attendance.subject_categories (category_id, category_name) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Core'),
    (2, 'Professional Elective'),
    (3, 'Open Elective'),
    (4, 'Lab'),
    (5, 'Audit Course')
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO attendance.subjects (
    subject_id, subject_code, subject_name, category_id, department_id, semester_no, credits, total_hours, is_lab
) OVERRIDING SYSTEM VALUE VALUES
    (1, 'CS201', 'Data Structures', 1, 1, 3, 4.0, 60, false),
    (2, 'CS301', 'Database Management Systems', 1, 1, 4, 4.0, 60, false),
    (3, 'MC4261', 'Data Visualization', 1, 2, 2, 4.0, 60, false),
    (4, 'MC4268', 'Mini Project', 4, 2, 2, 2.0, 30, true)
ON CONFLICT (subject_id) DO NOTHING;

INSERT INTO attendance.classrooms (classroom_id, room_number, block_name, floor_no, capacity, has_cctv) OVERRIDING SYSTEM VALUE VALUES
    (1, '508', 'CSE Block', 5, 70, true),
    (2, '509', 'CSE Block', 5, 70, true),
    (3, '510', 'CSE Block', 5, 70, true)
ON CONFLICT (classroom_id) DO NOTHING;

INSERT INTO attendance.periods (period_id, period_no, start_time, end_time, duration_minutes) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, '08:15', '09:05', 50),
    (2, 2, '09:05', '09:55', 50),
    (3, 3, '10:10', '11:00', 50),
    (4, 4, '11:00', '11:50', 50),
    (5, 5, '12:30', '13:20', 50),
    (6, 6, '13:20', '14:10', 50),
    (7, 7, '14:20', '15:10', 50)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO attendance.sections (
    section_id, department_id, program_id, academic_year_id, semester_id, section_name, strength
) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 1, 1, 3, 'II Year A', 70),
    (2, 1, 1, 1, 3, 'II Year B', 70),
    (3, 2, 2, 1, 1, 'MCA II', 120)
ON CONFLICT (section_id) DO NOTHING;

-- password_hash is not a valid bcrypt string on purpose. Set real hashes before login.
INSERT INTO attendance.users (
    user_id, username, password_hash, role_id, department_id, first_name, email, status
) OVERRIDING SYSTEM VALUE VALUES
    (1, 'superadmin', '*unusable*', 1, 1, 'System', 'superadmin@srmvec.edu', 'inactive'),
    (2, 'hod_cse', '*unusable*', 3, 1, 'Head', 'hodcse@srmvec.edu', 'inactive'),
    (3, 'faculty_cse', '*unusable*', 5, 1, 'Faculty', 'faculty.cse@srmvec.edu', 'inactive'),
    (4, '22CS001', '*unusable*', 6, 1, 'Student1', NULL, 'inactive'),
    (5, '22CS002', '*unusable*', 6, 1, 'Student2', NULL, 'inactive'),
    (6, '22MC001', '*unusable*', 6, 2, 'MCAStudent', NULL, 'inactive')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO attendance.staff (staff_id, user_id, staff_code, designation, department_id, status) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 'SA001', 'System Administrator', 1, 'active'),
    (2, 2, 'HOD001', 'Professor & HOD', 1, 'active'),
    (3, 3, 'CSE101', 'Assistant Professor', 1, 'active')
ON CONFLICT (staff_id) DO NOTHING;

UPDATE attendance.departments SET hod_staff_id = 2 WHERE department_id = 1 AND hod_staff_id IS NULL;

INSERT INTO identity.cameras (camera_id, location_label, source_ref, classroom_id, enabled) VALUES
    ('CSE-510-FRONT', 'CSE Block 510 front', 'camera/cse-510-front', 3, true)
ON CONFLICT (camera_id) DO NOTHING;

INSERT INTO identity.students (
    university_id, full_name, user_id, section_id, register_no, batch_year, enrollment_status
) VALUES
    ('22CS001', 'Student1', 4, 1, '22CS001', 2022, 'active'),
    ('22CS002', 'Student2', 5, 1, '22CS002', 2022, 'active'),
    ('22MC001', 'MCAStudent', 6, 3, '22MC001', 2025, 'active')
ON CONFLICT (university_id) DO NOTHING;

INSERT INTO attendance.timetable (
    timetable_id, academic_year_id, semester_id, section_id, subject_id,
    staff_id, classroom_id, day_of_week, period_id, is_active
) OVERRIDING SYSTEM VALUE VALUES
    (1, 1, 3, 1, 1, 3, 3, 1, 1, true)
ON CONFLICT (timetable_id) DO NOTHING;

INSERT INTO attendance.system_settings (setting_key, setting_value, description) VALUES
    ('college_name', 'SRM Valliammai Engineering College', NULL),
    ('attendance_threshold_percent', '75', 'Defaulter cutoff'),
    ('present_min_minutes', '45', 'Minimum presence in period to count as Present'),
    ('late_min_minutes', '15', 'Below present_min and at/above this counts as Late'),
    ('period_duration_minutes', '50', NULL)
ON CONFLICT (setting_key) DO NOTHING;

SELECT setval(pg_get_serial_sequence('attendance.roles', 'role_id'), (SELECT MAX(role_id) FROM attendance.roles));
SELECT setval(pg_get_serial_sequence('attendance.departments', 'department_id'), (SELECT MAX(department_id) FROM attendance.departments));
SELECT setval(pg_get_serial_sequence('attendance.programs', 'program_id'), (SELECT MAX(program_id) FROM attendance.programs));
SELECT setval(pg_get_serial_sequence('attendance.academic_years', 'academic_year_id'), (SELECT MAX(academic_year_id) FROM attendance.academic_years));
SELECT setval(pg_get_serial_sequence('attendance.semesters', 'semester_id'), (SELECT MAX(semester_id) FROM attendance.semesters));
SELECT setval(pg_get_serial_sequence('attendance.subject_categories', 'category_id'), (SELECT MAX(category_id) FROM attendance.subject_categories));
SELECT setval(pg_get_serial_sequence('attendance.subjects', 'subject_id'), (SELECT MAX(subject_id) FROM attendance.subjects));
SELECT setval(pg_get_serial_sequence('attendance.classrooms', 'classroom_id'), (SELECT MAX(classroom_id) FROM attendance.classrooms));
SELECT setval(pg_get_serial_sequence('attendance.periods', 'period_id'), (SELECT MAX(period_id) FROM attendance.periods));
SELECT setval(pg_get_serial_sequence('attendance.sections', 'section_id'), (SELECT MAX(section_id) FROM attendance.sections));
SELECT setval(pg_get_serial_sequence('attendance.users', 'user_id'), (SELECT MAX(user_id) FROM attendance.users));
SELECT setval(pg_get_serial_sequence('attendance.staff', 'staff_id'), (SELECT MAX(staff_id) FROM attendance.staff));
SELECT setval(pg_get_serial_sequence('attendance.timetable', 'timetable_id'), (SELECT MAX(timetable_id) FROM attendance.timetable));

COMMIT;

-- Session default for new connections. Phase 1 uses unqualified table names.
ALTER DATABASE srm_attendance SET search_path TO identity, attendance, public;

